// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : brianpollack
Date           : Wed Nov 13 12:07:51 2013
Host           : Darwin pb-d-128-141-108-211.cern.ch 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64
Dir            : /Users/brianpollack/HZG_Analyzer/mva
Training events: 15120
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
medisc                        medisc                        medisc                        -log(Pb/(Ps+Pb))                                                'F'    [-0,0.215531349182]
smallTheta                    smallTheta                    smallTheta                    cos(#theta)                                                     'F'    [-0.988485515118,0.985404670238]
bigTheta                      bigTheta                      bigTheta                      cos(#Theta)                                                     'F'    [-0.999703705311,0.99986243248]
comPhi                        comPhi                        comPhi                        #phi                          rad                               'F'    [-3.14131355286,3.14112186432]
GPtOM                         GPtOM                         GPtOM                         #pT_{#gamma}/m_{ll#gamma}                                       'F'    [0.1363671422,1.45451247692]
diffZGvectorOM                diffZGvectorOM                diffZGvectorOM                (#pT_{#gamma}-pT_{ll})/m_{ll#gamma}                                  'F'    [0.00167611835059,3.01243019104]
threeBodyPtOM                 threeBodyPtOM                 threeBodyPtOM                 #pT_{ll#gamma}/m_{ll#gamma}                                     'F'    [0.0011086530285,4.17393541336]
ZPtOM                         ZPtOM                         ZPtOM                         #pT_{ll}/m_{ll#gamma}                                           'F'    [0.00158683862537,3.55387020111]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "medisc", "smallTheta", "bigTheta", "comPhi", "GPtOM", "diffZGvectorOM", "threeBodyPtOM", "ZPtOM" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[14][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][14];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.342791121914375;
   fWeightMatrix0to1[1][0] = 1.02284812222958;
   fWeightMatrix0to1[2][0] = 2.34402837546796;
   fWeightMatrix0to1[3][0] = 1.1284685786782;
   fWeightMatrix0to1[4][0] = -1.52062834678498;
   fWeightMatrix0to1[5][0] = -1.2355944040477;
   fWeightMatrix0to1[6][0] = 0.192261637724064;
   fWeightMatrix0to1[7][0] = 1.2693952317385;
   fWeightMatrix0to1[8][0] = -1.50297214952135;
   fWeightMatrix0to1[9][0] = -1.15998284580966;
   fWeightMatrix0to1[10][0] = -0.910356530895286;
   fWeightMatrix0to1[11][0] = -0.0239128833767216;
   fWeightMatrix0to1[12][0] = -1.05371732006777;
   fWeightMatrix0to1[0][1] = -0.392509336612725;
   fWeightMatrix0to1[1][1] = -0.456426214314218;
   fWeightMatrix0to1[2][1] = -0.0309999960700831;
   fWeightMatrix0to1[3][1] = 0.0809366556565045;
   fWeightMatrix0to1[4][1] = 0.11978659053447;
   fWeightMatrix0to1[5][1] = 0.00178767412894465;
   fWeightMatrix0to1[6][1] = -0.0812206382681097;
   fWeightMatrix0to1[7][1] = -0.121546921621648;
   fWeightMatrix0to1[8][1] = -0.0517107815353265;
   fWeightMatrix0to1[9][1] = 0.211616503035185;
   fWeightMatrix0to1[10][1] = -0.0380501642636549;
   fWeightMatrix0to1[11][1] = -0.290671629223564;
   fWeightMatrix0to1[12][1] = -0.0402771889442665;
   fWeightMatrix0to1[0][2] = 0.77680463587146;
   fWeightMatrix0to1[1][2] = 0.682268316333325;
   fWeightMatrix0to1[2][2] = -2.67256915398955;
   fWeightMatrix0to1[3][2] = -0.437317642402125;
   fWeightMatrix0to1[4][2] = 1.69646758639454;
   fWeightMatrix0to1[5][2] = 1.08737021465726;
   fWeightMatrix0to1[6][2] = -0.246383490667078;
   fWeightMatrix0to1[7][2] = 0.334713732587717;
   fWeightMatrix0to1[8][2] = 0.996140596456625;
   fWeightMatrix0to1[9][2] = -0.733913546349487;
   fWeightMatrix0to1[10][2] = -0.541830668685568;
   fWeightMatrix0to1[11][2] = 0.906724824097096;
   fWeightMatrix0to1[12][2] = -1.13362643016543;
   fWeightMatrix0to1[0][3] = 0.260399258170455;
   fWeightMatrix0to1[1][3] = 0.428485974677812;
   fWeightMatrix0to1[2][3] = 0.143196551185252;
   fWeightMatrix0to1[3][3] = 0.092945058460113;
   fWeightMatrix0to1[4][3] = 0.0332981755416514;
   fWeightMatrix0to1[5][3] = -0.568179774489649;
   fWeightMatrix0to1[6][3] = -0.11311880986995;
   fWeightMatrix0to1[7][3] = 0.182443316362678;
   fWeightMatrix0to1[8][3] = -0.140356456696896;
   fWeightMatrix0to1[9][3] = -0.134013779695446;
   fWeightMatrix0to1[10][3] = 1.13933269556228;
   fWeightMatrix0to1[11][3] = 1.01256304392938;
   fWeightMatrix0to1[12][3] = -0.0883028286985233;
   fWeightMatrix0to1[0][4] = -1.47786568189828;
   fWeightMatrix0to1[1][4] = 0.568350596216376;
   fWeightMatrix0to1[2][4] = 0.730501058061469;
   fWeightMatrix0to1[3][4] = -0.813135597809492;
   fWeightMatrix0to1[4][4] = -1.27852336519146;
   fWeightMatrix0to1[5][4] = -1.59704060968828;
   fWeightMatrix0to1[6][4] = 2.12189229781769;
   fWeightMatrix0to1[7][4] = 0.93978543268774;
   fWeightMatrix0to1[8][4] = -3.84273925274993;
   fWeightMatrix0to1[9][4] = 1.85927801540376;
   fWeightMatrix0to1[10][4] = -0.755298687804274;
   fWeightMatrix0to1[11][4] = 0.701926288187725;
   fWeightMatrix0to1[12][4] = 2.44029195787877;
   fWeightMatrix0to1[0][5] = -0.22921960769594;
   fWeightMatrix0to1[1][5] = 0.149477461496103;
   fWeightMatrix0to1[2][5] = -0.944167643596125;
   fWeightMatrix0to1[3][5] = 1.58493114279522;
   fWeightMatrix0to1[4][5] = -1.27340224844547;
   fWeightMatrix0to1[5][5] = -0.661578904156794;
   fWeightMatrix0to1[6][5] = -1.8910394156646;
   fWeightMatrix0to1[7][5] = 2.27338724759226;
   fWeightMatrix0to1[8][5] = 0.271520730016666;
   fWeightMatrix0to1[9][5] = 1.8779953422209;
   fWeightMatrix0to1[10][5] = -0.384026024649981;
   fWeightMatrix0to1[11][5] = -1.02521836168157;
   fWeightMatrix0to1[12][5] = -5.12629901869268;
   fWeightMatrix0to1[0][6] = 1.57938672655985;
   fWeightMatrix0to1[1][6] = 0.574533049669743;
   fWeightMatrix0to1[2][6] = 1.66839467336551;
   fWeightMatrix0to1[3][6] = 0.244995590330347;
   fWeightMatrix0to1[4][6] = 0.453180738554778;
   fWeightMatrix0to1[5][6] = -0.734634320931762;
   fWeightMatrix0to1[6][6] = -0.421938212544191;
   fWeightMatrix0to1[7][6] = -0.455405390267992;
   fWeightMatrix0to1[8][6] = -0.0298787407348461;
   fWeightMatrix0to1[9][6] = -1.38690063416334;
   fWeightMatrix0to1[10][6] = -0.866391729006596;
   fWeightMatrix0to1[11][6] = -1.20756110547307;
   fWeightMatrix0to1[12][6] = 2.53183585336949;
   fWeightMatrix0to1[0][7] = -0.228372150729637;
   fWeightMatrix0to1[1][7] = 1.81090489929541;
   fWeightMatrix0to1[2][7] = -2.18875072902034;
   fWeightMatrix0to1[3][7] = -0.363914800251331;
   fWeightMatrix0to1[4][7] = 0.980521728390338;
   fWeightMatrix0to1[5][7] = -0.802744882661642;
   fWeightMatrix0to1[6][7] = -2.30262088462979;
   fWeightMatrix0to1[7][7] = 1.20676656359678;
   fWeightMatrix0to1[8][7] = 0.756309658116121;
   fWeightMatrix0to1[9][7] = -2.05257728060397;
   fWeightMatrix0to1[10][7] = -1.0052730208584;
   fWeightMatrix0to1[11][7] = 1.12308488095229;
   fWeightMatrix0to1[12][7] = 0.0169229814456736;
   fWeightMatrix0to1[0][8] = -0.500863582378404;
   fWeightMatrix0to1[1][8] = 1.39509895804813;
   fWeightMatrix0to1[2][8] = 0.0282848359967362;
   fWeightMatrix0to1[3][8] = -0.630069992877403;
   fWeightMatrix0to1[4][8] = -0.352295552305413;
   fWeightMatrix0to1[5][8] = 0.254323695315959;
   fWeightMatrix0to1[6][8] = -1.37334687405527;
   fWeightMatrix0to1[7][8] = 4.59336122690851;
   fWeightMatrix0to1[8][8] = -2.15549844507311;
   fWeightMatrix0to1[9][8] = -0.628211367058851;
   fWeightMatrix0to1[10][8] = -1.9009848790161;
   fWeightMatrix0to1[11][8] = 1.83724047564039;
   fWeightMatrix0to1[12][8] = 1.6532044828574;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.962562071786965;
   fWeightMatrix1to2[0][1] = 0.636689368121679;
   fWeightMatrix1to2[0][2] = 0.340558831144317;
   fWeightMatrix1to2[0][3] = 0.70764088652839;
   fWeightMatrix1to2[0][4] = 0.598367828938536;
   fWeightMatrix1to2[0][5] = 0.100142177229203;
   fWeightMatrix1to2[0][6] = 0.472339539507418;
   fWeightMatrix1to2[0][7] = 0.785991811101928;
   fWeightMatrix1to2[0][8] = 0.709728508815428;
   fWeightMatrix1to2[0][9] = -1.01870998896052;
   fWeightMatrix1to2[0][10] = 0.116904604313867;
   fWeightMatrix1to2[0][11] = -0.333938609984232;
   fWeightMatrix1to2[0][12] = 0.959116015901178;
   fWeightMatrix1to2[0][13] = -0.710871125863291;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5.42403722648e-06;
   fMax_1[0][0] = 0.163225084543;
   fMin_1[1][0] = -0;
   fMax_1[1][0] = 0.215531349182;
   fMin_1[2][0] = -0;
   fMax_1[2][0] = 0.215531349182;
   fMin_1[0][1] = -0.981812477112;
   fMax_1[0][1] = 0.985404670238;
   fMin_1[1][1] = -0.988485515118;
   fMax_1[1][1] = 0.985260605812;
   fMin_1[2][1] = -0.988485515118;
   fMax_1[2][1] = 0.985404670238;
   fMin_1[0][2] = -0.996503174305;
   fMax_1[0][2] = 0.998501420021;
   fMin_1[1][2] = -0.999703705311;
   fMax_1[1][2] = 0.99986243248;
   fMin_1[2][2] = -0.999703705311;
   fMax_1[2][2] = 0.99986243248;
   fMin_1[0][3] = -3.14131355286;
   fMax_1[0][3] = 3.14039206505;
   fMin_1[1][3] = -3.14012765884;
   fMax_1[1][3] = 3.14112186432;
   fMin_1[2][3] = -3.14131355286;
   fMax_1[2][3] = 3.14112186432;
   fMin_1[0][4] = 0.1363671422;
   fMax_1[0][4] = 1.05999577045;
   fMin_1[1][4] = 0.136370569468;
   fMax_1[1][4] = 1.45451247692;
   fMin_1[2][4] = 0.1363671422;
   fMax_1[2][4] = 1.45451247692;
   fMin_1[0][5] = 0.0108523620293;
   fMax_1[0][5] = 3.01243019104;
   fMin_1[1][5] = 0.00167611835059;
   fMax_1[1][5] = 2.6240503788;
   fMin_1[2][5] = 0.00167611835059;
   fMax_1[2][5] = 3.01243019104;
   fMin_1[0][6] = 0.00173675955739;
   fMax_1[0][6] = 4.17393541336;
   fMin_1[1][6] = 0.0011086530285;
   fMax_1[1][6] = 2.93508195877;
   fMin_1[2][6] = 0.0011086530285;
   fMax_1[2][6] = 4.17393541336;
   fMin_1[0][7] = 0.00279403431341;
   fMax_1[0][7] = 3.55387020111;
   fMin_1[1][7] = 0.00158683862537;
   fMax_1[1][7] = 2.77956628799;
   fMin_1[2][7] = 0.00158683862537;
   fMax_1[2][7] = 3.55387020111;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
