// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : brianpollack
Date           : Wed Nov 13 13:09:51 2013
Host           : Darwin pb-d-128-141-108-211.cern.ch 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64
Dir            : /Users/brianpollack/HZG_Analyzer/mva
Training events: 15120
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
smallTheta                    smallTheta                    smallTheta                    cos(#theta)                                                     'F'    [-0.988485515118,0.985404670238]
bigTheta                      bigTheta                      bigTheta                      cos(#Theta)                                                     'F'    [-0.999703705311,0.99986243248]
comPhi                        comPhi                        comPhi                        #phi                          rad                               'F'    [-3.14131355286,3.14112186432]
GPtOM                         GPtOM                         GPtOM                         #pT_{#gamma}/m_{ll#gamma}                                       'F'    [0.1363671422,1.45451247692]
diffZGvectorOM                diffZGvectorOM                diffZGvectorOM                (#pT_{#gamma}-pT_{ll})/m_{ll#gamma}                                  'F'    [0.00167611835059,3.01243019104]
threeBodyPtOM                 threeBodyPtOM                 threeBodyPtOM                 #pT_{ll#gamma}/m_{ll#gamma}                                     'F'    [0.0011086530285,4.17393541336]
ZPtOM                         ZPtOM                         ZPtOM                         #pT_{ll}/m_{ll#gamma}                                           'F'    [0.00158683862537,3.55387020111]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "smallTheta", "bigTheta", "comPhi", "GPtOM", "diffZGvectorOM", "threeBodyPtOM", "ZPtOM" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[13][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 13; fWeights[1] = new double[13]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.0541750823051182;
   fWeightMatrix0to1[1][0] = 1.01550822826723;
   fWeightMatrix0to1[2][0] = 1.48296048569291;
   fWeightMatrix0to1[3][0] = 0.914964825083407;
   fWeightMatrix0to1[4][0] = -0.0264193052725027;
   fWeightMatrix0to1[5][0] = 0.00596565544913249;
   fWeightMatrix0to1[6][0] = 0.0212671232706301;
   fWeightMatrix0to1[7][0] = 0.733024930649897;
   fWeightMatrix0to1[8][0] = -0.481286449317643;
   fWeightMatrix0to1[9][0] = -0.741887604703636;
   fWeightMatrix0to1[10][0] = -0.0275651280728918;
   fWeightMatrix0to1[11][0] = -0.139108222217436;
   fWeightMatrix0to1[0][1] = -0.567211767358046;
   fWeightMatrix0to1[1][1] = 0.531719029599817;
   fWeightMatrix0to1[2][1] = -0.0192305635518457;
   fWeightMatrix0to1[3][1] = 0.0562234300766283;
   fWeightMatrix0to1[4][1] = -1.01225652670299;
   fWeightMatrix0to1[5][1] = 2.38142693076427;
   fWeightMatrix0to1[6][1] = -1.05146844796986;
   fWeightMatrix0to1[7][1] = 0.824560251066217;
   fWeightMatrix0to1[8][1] = -0.614564802909926;
   fWeightMatrix0to1[9][1] = -0.990814810224968;
   fWeightMatrix0to1[10][1] = -0.208184364419831;
   fWeightMatrix0to1[11][1] = -0.154347632975482;
   fWeightMatrix0to1[0][2] = 0.00508754296391056;
   fWeightMatrix0to1[1][2] = 0.0652148036187735;
   fWeightMatrix0to1[2][2] = -0.261770055581123;
   fWeightMatrix0to1[3][2] = -0.00608742796653237;
   fWeightMatrix0to1[4][2] = -0.0344230312872964;
   fWeightMatrix0to1[5][2] = -0.0912421720751652;
   fWeightMatrix0to1[6][2] = -0.0664862842965385;
   fWeightMatrix0to1[7][2] = 0.252922708899676;
   fWeightMatrix0to1[8][2] = -0.0253819973131316;
   fWeightMatrix0to1[9][2] = -0.375006503386991;
   fWeightMatrix0to1[10][2] = 0.0953196828175179;
   fWeightMatrix0to1[11][2] = -0.11379085252481;
   fWeightMatrix0to1[0][3] = -2.0809705579522;
   fWeightMatrix0to1[1][3] = 2.30886598804224;
   fWeightMatrix0to1[2][3] = -1.69126658813414;
   fWeightMatrix0to1[3][3] = 1.25060780008305;
   fWeightMatrix0to1[4][3] = -0.819558969039581;
   fWeightMatrix0to1[5][3] = -4.68955949147663;
   fWeightMatrix0to1[6][3] = 5.22109018775263;
   fWeightMatrix0to1[7][3] = 1.61000207717934;
   fWeightMatrix0to1[8][3] = -1.36242926735208;
   fWeightMatrix0to1[9][3] = -1.55436584188258;
   fWeightMatrix0to1[10][3] = 5.73184548372503;
   fWeightMatrix0to1[11][3] = 0.935147889838222;
   fWeightMatrix0to1[0][4] = -1.50939890358447;
   fWeightMatrix0to1[1][4] = 0.862558069170039;
   fWeightMatrix0to1[2][4] = 0.467042134048663;
   fWeightMatrix0to1[3][4] = 1.31186045469433;
   fWeightMatrix0to1[4][4] = -1.07739049880471;
   fWeightMatrix0to1[5][4] = -0.409945892439226;
   fWeightMatrix0to1[6][4] = -1.13452079184814;
   fWeightMatrix0to1[7][4] = -0.649363246184774;
   fWeightMatrix0to1[8][4] = -1.29949781178238;
   fWeightMatrix0to1[9][4] = -0.429417699085649;
   fWeightMatrix0to1[10][4] = 6.72643222602135;
   fWeightMatrix0to1[11][4] = -1.2648245807368;
   fWeightMatrix0to1[0][5] = -2.57866618766702;
   fWeightMatrix0to1[1][5] = 0.0959044050145535;
   fWeightMatrix0to1[2][5] = -0.825158349600881;
   fWeightMatrix0to1[3][5] = 0.736969796542581;
   fWeightMatrix0to1[4][5] = 0.748088650290843;
   fWeightMatrix0to1[5][5] = 0.244878495387798;
   fWeightMatrix0to1[6][5] = 1.03044805167651;
   fWeightMatrix0to1[7][5] = -1.10780868967597;
   fWeightMatrix0to1[8][5] = 0.0150007648913701;
   fWeightMatrix0to1[9][5] = -0.664879079834292;
   fWeightMatrix0to1[10][5] = -5.1066673702181;
   fWeightMatrix0to1[11][5] = -1.85011763169811;
   fWeightMatrix0to1[0][6] = 0.693152375490438;
   fWeightMatrix0to1[1][6] = 0.220540789933352;
   fWeightMatrix0to1[2][6] = 1.27821585958888;
   fWeightMatrix0to1[3][6] = -0.0592802715489511;
   fWeightMatrix0to1[4][6] = -2.09922066661439;
   fWeightMatrix0to1[5][6] = 1.28769058817547;
   fWeightMatrix0to1[6][6] = -0.0531296894877971;
   fWeightMatrix0to1[7][6] = 0.972062608186633;
   fWeightMatrix0to1[8][6] = 1.5408223842525;
   fWeightMatrix0to1[9][6] = 1.52339045806008;
   fWeightMatrix0to1[10][6] = 0.707375214044166;
   fWeightMatrix0to1[11][6] = -1.45849076089665;
   fWeightMatrix0to1[0][7] = -4.03423030934543;
   fWeightMatrix0to1[1][7] = 0.397948432187083;
   fWeightMatrix0to1[2][7] = 1.38262739328004;
   fWeightMatrix0to1[3][7] = -1.28703733039126;
   fWeightMatrix0to1[4][7] = -2.784382212796;
   fWeightMatrix0to1[5][7] = -2.72116635345124;
   fWeightMatrix0to1[6][7] = 5.16699182770946;
   fWeightMatrix0to1[7][7] = 0.371548735396878;
   fWeightMatrix0to1[8][7] = 1.29489018592623;
   fWeightMatrix0to1[9][7] = -0.531156981209605;
   fWeightMatrix0to1[10][7] = 4.66530235843444;
   fWeightMatrix0to1[11][7] = -0.166224861305845;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.04365177648344;
   fWeightMatrix1to2[0][1] = 0.0514559429204793;
   fWeightMatrix1to2[0][2] = -0.197982508165213;
   fWeightMatrix1to2[0][3] = -0.254445374866314;
   fWeightMatrix1to2[0][4] = -1.83706593726257;
   fWeightMatrix1to2[0][5] = -0.355075802787961;
   fWeightMatrix1to2[0][6] = 1.03875931181053;
   fWeightMatrix1to2[0][7] = -0.65529230533226;
   fWeightMatrix1to2[0][8] = -0.759948663417753;
   fWeightMatrix1to2[0][9] = -0.486141707127386;
   fWeightMatrix1to2[0][10] = -0.88002709555451;
   fWeightMatrix1to2[0][11] = -0.644830128223421;
   fWeightMatrix1to2[0][12] = -0.0101072420081108;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -0.981812477112;
   fMax_1[0][0] = 0.985404670238;
   fMin_1[1][0] = -0.988485515118;
   fMax_1[1][0] = 0.985260605812;
   fMin_1[2][0] = -0.988485515118;
   fMax_1[2][0] = 0.985404670238;
   fMin_1[0][1] = -0.996503174305;
   fMax_1[0][1] = 0.998501420021;
   fMin_1[1][1] = -0.999703705311;
   fMax_1[1][1] = 0.99986243248;
   fMin_1[2][1] = -0.999703705311;
   fMax_1[2][1] = 0.99986243248;
   fMin_1[0][2] = -3.14131355286;
   fMax_1[0][2] = 3.14039206505;
   fMin_1[1][2] = -3.14012765884;
   fMax_1[1][2] = 3.14112186432;
   fMin_1[2][2] = -3.14131355286;
   fMax_1[2][2] = 3.14112186432;
   fMin_1[0][3] = 0.1363671422;
   fMax_1[0][3] = 1.05999577045;
   fMin_1[1][3] = 0.136370569468;
   fMax_1[1][3] = 1.45451247692;
   fMin_1[2][3] = 0.1363671422;
   fMax_1[2][3] = 1.45451247692;
   fMin_1[0][4] = 0.0108523620293;
   fMax_1[0][4] = 3.01243019104;
   fMin_1[1][4] = 0.00167611835059;
   fMax_1[1][4] = 2.6240503788;
   fMin_1[2][4] = 0.00167611835059;
   fMax_1[2][4] = 3.01243019104;
   fMin_1[0][5] = 0.00173675955739;
   fMax_1[0][5] = 4.17393541336;
   fMin_1[1][5] = 0.0011086530285;
   fMax_1[1][5] = 2.93508195877;
   fMin_1[2][5] = 0.0011086530285;
   fMax_1[2][5] = 4.17393541336;
   fMin_1[0][6] = 0.00279403431341;
   fMax_1[0][6] = 3.55387020111;
   fMin_1[1][6] = 0.00158683862537;
   fMax_1[1][6] = 2.77956628799;
   fMin_1[2][6] = 0.00158683862537;
   fMax_1[2][6] = 3.55387020111;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
